#!/usr/bin/env bash

where=$1 || .
tests=$1
if [ -d $where ]; then
  tests=`find $where -type d -name __tests__ -not -path './node_modules/*'`
fi

./node_modules/.bin/mocha $2 --compilers js:babel/register $tests
